### ISSUE TITLE
Use overflow-wrap: anywhere; instead of overflow-wrap: break-word;

### ISSUE THREAD

**Issue by tamanyan** [google/budoux#143]
## Motivation

If `display: flex;` is applied to the parent element, the `overflow-wrap: break-word;`  becomes ineffective, resulting in text overflow.

`overflow-wrap: anywhere;` resolves the issue. It's supported on modern web browsers.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

<img width="959" alt="Screen Shot 2023-05-26 at 14 57 39" src="https://github.com/google/budoux/assets/2387508/a886ffd7-ff6d-41e6-8704-84221b5cf108">

## Key points

The primary difference between `overflow-wrap: anywhere;` and `overflow-wrap: break-word` is reflected in the way soft wrap opportunities introduced by word-break are handled when calculating **min-content intrinsic sizes**.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

> anywhere
> To prevent overflow, an otherwise unbreakable string of characters — like a long word or URL — may be broken at any point if there are no otherwise-acceptable break points in the line. No hyphenation character is inserted at the break point. Soft wrap opportunities introduced by the word break are considered when calculating min-content intrinsic sizes.

> break-word
> The same as the anywhere value, with normally unbreakable words allowed to be broken at arbitrary points if there are no otherwise acceptable break points in the line, but soft wrap opportunities introduced by the word break are NOT considered when calculating min-content intrinsic sizes.

## Steps to reproduce

Go to the example https://codepen.io/tamanyan/pen/KKyyxMj

<img width="536" alt="Screen Shot 2023-05-26 at 14 51 52" src="https://github.com/google/budoux/assets/2387508/723c2319-7f2c-43c9-828b-223aecca2897">

```html
<div class="flex">
  <div>
    <h3>5. word-break: keep-all; + overflow-wrap: break-word; + &lt;wbr&gt;  + flex</h3>
    <p class="keep-all-break-word box">
      グレートブリテン<wbr>および<wbr>北アイルランド連合王国という<wbr>言葉は<wbr>本当に<wbr>長い言葉<wbr>ですね
    </p>
  </div>
</div>
```

```css
.flex {
  display: flex;
}

.keep-all-break-word {
  word-break: keep-all;
  overflow-wrap: break-word;
}

.box {
  padding: 10px;
  border: 1px solid;
  font-size: 40px;
}
```

## Proposal

Use overflow-wrap: anywhere; instead of overflow-wrap: break-word;

**Comment by tushuhei** [comment]
Fixed by #144
