### ISSUE TITLE
[quality] あなたの意図したとおりに情報を伝えることができます。

### ISSUE THREAD

**Issue by kojiishi** [google/budoux#216]
Input: あなたの意図したとおりに情報を伝えることができます。
Actual:
あなたの/意図したと/おりに/情報を/伝える/ことができます。
Expected:
あなたの/意図したとおりに/情報を/伝える/ことができます。
あなたの/意図した/とおりに/情報を/伝える/ことが/できます。

Found in Blink web_tests.

**Comment by tushuhei** [comment]
Fixed by #410
