### ISSUE TITLE
[quality] あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。

### ISSUE THREAD

**Issue by kojiishi** [google/budoux#220]
Input:
あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。
Actual:
あの/イーハトーヴォの/すきと/おった/風、/夏でも/底に/冷たさを/もつ青い/そら、/うつくしい/森で/飾られた/モリーオ市、/郊外の/ぎらぎら/ひかる/草の/波。
Expected:
あの/イーハトーヴォの/すきとおった/風、/夏でも/底に/冷たさを/もつ/青い/そら、/うつくしい/森で/飾られた/モリーオ市、/郊外の/ぎらぎら/ひかる/草の/波。

**Comment by tushuhei** [comment]
Fixed by #410
