### ISSUE TITLE
[java] `HTMLProcessor.getText()` collapses whitespaces

### ISSUE THREAD

**Issue by kojiishi** [google/budoux#366]
`HTMLProcessor.getText()` calls:
```java
    return Jsoup.parseBodyFragment(html).text();
```

It looks like this collapses whitespaces. Example:
```java
    String html = " H      e ";
    String result = HTMLProcessor.getText(html);
```
The `result` becomes `H e`, collapsing consecutive spaces into one space, and leading and trailing spaces to none.

/cc @tushuhei

**Comment by kojiishi** [comment]
Using `wholeText()` instead seems to solve it, but It also converts `<br>` to LF (U+0010).

Options:
a. Make the visitor match the behavior of `wholeText()`.
b. Use another visitor and our own logic for `getText()`.

Which do we prefer?

**Comment by tushuhei** [comment]
Thanks for your thorough investigation! I prefer the option a, switching `text()` to `wholeText()` and making adjustment.
