### ISSUE TITLE
to fixed number line

### ISSUE THREAD

**Issue by wanghaisheng** [google/budoux#45]
can i set parameter to let budoux output fixed line

**Comment by tushuhei** [comment]
Hi! Could you clarify what the fixed line means with some examples? What's the ideal output expected?

**Comment by wanghaisheng** [comment]
never mind ,I  managed to that.for example as following.
default as this
```
echo $'本日は晴天です。\n明日は曇りでしょう。' | budoux
本日は
晴天です。
---
明日は
曇りでしょう。
```
what I  want is fixed line let say 2 because I want to limit words/characters in each line ,then I  cal and join the first and last 3 line into new line 
@tushuhei

**Comment by tushuhei** [comment]
Hmm, sorry I think I need some more clarification.
What is the ideal output for the command `echo $'本日は晴天です。\n明日は曇りでしょう。' | budoux` with the parameter you want to have?

**Comment by wanghaisheng** [comment]
since i really dont know japanese ,perhaps this text example isnt that proper, my case is i want to cut long paragpraph into small ones without cutting from middle of sentence, i found your lib is kinda of can do this job.
my idea came into first get raw output of budouX,then line by line count the total words ,

**Comment by tushuhei** [comment]
Yes, BudouX can be used to separate a long paragraph into a series of phrases.
If you're interested in counting the phrases (or words) in total, I believe you can get the desired results using `sed` and `wc` like this:

```
echo $'本日は晴天です。\n明日は曇りでしょう。' | budoux -d='' | sed  '/^$/d' | wc -l
```

**Comment by tushuhei** [comment]
Closing this bug for now, but fee free to reopen if anything.

**Comment by g1ra** [comment]
I'm looking for the same . : takes a string as input and breaks it into lines based on the maximum number of characters per line specified by the user, ensuring that no word is split in the middle. Words longer than the specified maximum characters should be placed on their own line.
