### ISSUE TITLE
Chrome M121 breaks <ruby> unittest

### ISSUE THREAD

**Issue by tushuhei** [google/budoux#476]
A JavaScript unit test case is failing at https://github.com/google/budoux/actions/runs/7726982481/job/21064428934

```
 HTMLProcessor.getBlocks should skip <rt> and <rp> elements for <ruby> FAILED
```

Since the same test case passes on Chrome Headless M120, but not on M121, I believe the change is brought by the Chrome update.

**Comment by tushuhei** [comment]
@kojiishi Could you take a look at this? It seems the `<ruby>` tag is treated differently between Chrome M120 and 121.

**Comment by kojiishi** [comment]
Thanks, I'll take a look. /cc @tkent-google

**Comment by kojiishi** [comment]
So there was a spec change. The current BudouX has a logic to determine if an element is inline or block:
```javascript
      return display === 'inline' ? DomAction.Inline : DomAction.Block;
````
This no longer works since crbug.com/880802, as `getComputedStyle(<ruby>).display` returns `ruby`.

**Comment by tushuhei** [comment]
That’s interesting! Thanks for investigating.
Does it make sense to map `display==='ruby'` to `DomAction.Inline`, then?
