### ISSUE TITLE
Implementing of budoux in Webflow Website.

### ISSUE THREAD

**Issue by anupuxdesigner** [google/budoux#726]
![budoux](https://github.com/user-attachments/assets/c0606a6b-2cb6-4a48-bd93-3549e6819492)
I wanted to implement Budoux for a Japanese website in Webflow. I applied CDN, but using the import function was giving errors, saying unable to import.

I tried another workaround to add HTML embed as text and enclose it in Budoux like 
"<budoux-ja>Google の​使命は、​世界中の​情報を​整理し、​世界中の​人が​アクセスできて​使えるように​する​ことです。</budoux-ja>"
It worked!
but,
It would be good if, instead of using HTML embed element, I could use attributes to apply Budoux directly to my native Webflow text elements. I tried using "budou-this=true" , and , "budou-this=ja" but it did not worked. I don't know if i can use it with attributes or not.

![budoux attributes](https://github.com/user-attachments/assets/d8e93021-7256-4206-b1d9-5171de740236)

**Comment by tushuhei** [comment]
Hi there, thanks for reporting! Webflow is new to me, and I'm not sure if I can help make BudouX work the way you want.

>  I applied CDN, but using the import function was giving errors, saying unable to import.

Could you please clarify which CDN you used and the specific error message you encountered?

It's important to note that the BudouX JavaScript module is exported in two ways: CommonJS and ES Modules. While CommonJS is the default, only ES Modules function correctly within a web browser.

For instance, loading the script from `https://unpkg.com/budoux/` redirects to `dist/index.js`, which is a CommonJS module. To use ES Modules and ensure compatibility, load the script from `https://unpkg.com/budoux/module/index.js` instead.

**Comment by anupuxdesigner** [comment]
Hi,
I tried both modules, the problem is importing and parsing of element is
not working.
But I tried another way, I applied javascript which dynamically put my
element in <budoux-ja> and it worked!
Thanks for your reply.
Anup Singh

**Comment by tushuhei** [comment]
Great to hear that it's resolved!
