### ISSUE TITLE
JA parser returns not valid json

### ISSUE THREAD

**Issue by Yuri3K** [google/budoux#739]
![Screenshot_131](https://github.com/user-attachments/assets/a7a34caf-901a-4d85-a328-f2a2500c4336)
![Screenshot_132](https://github.com/user-attachments/assets/745401e4-aa40-4c77-bfd7-992c29b2725f)

If I process the json file with a parser (shown in the screenshot), I will get back an invalid json. The error occurs in cases where the string begins with the character "始". An error appears in the console (shown in the screenshot). At the moment, to avoid this error, I add a zero-width space before the character "始" directly to the json file. After such actions, the parser returns a valid json file.

PS. Thank you very much for your great library!

**Comment by tushuhei** [comment]
Hi, thanks for reporting! What character are you using to `join` the returned value of `this.parserJA.parse`? What happens if you use an empty character instead, i.e. `''`?
If the issue still persists, could you share the minimum `data` example that reproduces the error?
The screenshot below is my attempt to reproduce the error, but it worked fine.
![image](https://github.com/user-attachments/assets/91ac1b90-78e8-4051-ae7a-7e9f93484ea2)

**Comment by Yuri3K** [comment]
@tushuhei, hello

What character are you using to join the returned value of this.parserJA.parse?
Answer: the character is "zero-width-space"

What happens if you use an empty character instead, i.e. ''
Answer: If I use an empty character, app starts to work, but the library does not insert the zero-width-space character between words

I attached a zip file with a small Angular app, where you can explore the issue. 
[budoux-ja-app-master.zip](https://github.com/user-attachments/files/17154546/budoux-ja-app-master.zip)
You can also find it at the link below
https://github.com/Yuri3K/budoux-ja-app

Attached app is working, because in ja.json file I added a space before "始" character 
![Screenshot_144](https://github.com/user-attachments/assets/8243918f-bcee-4c88-986e-addc497247d2)

If you remove space before "始" character , you will get an arror in console.
![Screenshot_145](https://github.com/user-attachments/assets/b9129ddc-81b8-47a9-8953-a05df5c59488)

Parser is located in app.component.ts file. In this file you can get the "zero-width-space" character, that I used
![Screenshot_146](https://github.com/user-attachments/assets/4ace390b-e9a6-4e44-a8ea-57f180a90e35)

Thank you for your feedback!

**Comment by tushuhei** [comment]
Thanks for sharing the context. The root causation is that BudouX may insert ZWSP in a position that breaks the JSON syntax.
<img width="763" alt="image" src="https://github.com/user-attachments/assets/31d7c80c-e39c-48e5-9615-6a43d83ea08f">

I recommend applying BudouX only to object values, not the entire JSON serialized object. The code will look like:

```javascript
const result = Object.fromEntries(Object.entries(data).map(([key, value]) => [key, parser.parse(value).join(String.fromCharCode(0x200b))]));
```

**Comment by Yuri3K** [comment]
Thank you very much for the solution!
