### ISSUE TITLE
Issue with custom model

### ISSUE THREAD

**Issue by kefniark** [google/budoux#97]
## Description
Hi there,
First thanks for the lib, it's impressive the results from such a small footprint😄

The results were not exactly what I wanted for japanese tokenization, so I decided to train my own model and it was quite simple and straightforward. Sadly after importing the generated model in javascript it doesn't work.

```ts
import { Parser, loadDefaultJapaneseParser } from 'budoux'
import model from './mymodel.json'

// obviously the following works
const parser = loadDefaultJapaneseParser()
console.log(parser.parse('今日は天気です。'))

// but this doesn't
const parser = new Parser(model)
console.log(parser.parse('今日は天気です。'))
```

> Uncaught TypeError: this.model.values is not a function or its return value is not iterable
    at Parser.parse (parser.js:120:47)

**Comment by kefniark** [comment]
Ok looking at the code, I think I get it, it doesn't match the `Readme.md`

```ts
// this doesn't work
new Parser(model)

// but this work
new Parser(new Map(Object.entries(model)))
```
The model object need to be converted into a Map

**Comment by tushuhei** [comment]
Good catch! Thanks for your suggestion. I fixed the README accordingly.
